services:
    backend:
        image: sariko/sariko-backend:latest
        container_name: sariko-backend
        ports:
            - "5000:5000"
        volumes:
        - ../apps/logs:/www/logs
        env_file: ".env"

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/certbot/conf:/etc/letsencrypt
            - ./nginx/certbot/www:/var/www/certbot
        depends_on:
            - backend

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./nginx/certbot/conf:/etc/letsencrypt
            - ./nginx/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"  # Renew certificates every 12 hours