-- ============================================================
-- Users + user addresses
-- public.users.id mirrors auth.users.id (populated by the handle_user_create
-- trigger in functions/functions.sql).
-- ============================================================

create table public.users (
  id uuid not null default gen_random_uuid (),
  email text not null,
  name text null,
  phone text null,
  role text null default 'customer'::text,
  created_at timestamp without time zone null default now(),
  is_seller boolean null default false,
  updated_at timestamp without time zone null default now(),
  avatar_url text null,
  preferred_language text null,
  constraint users_pkey primary key (id),
  constraint users_email_key unique (email),
  constraint users_role_check check (
    (role = any (array['customer'::text, 'seller'::text]))
  )
) TABLESPACE pg_default;


create table public.user_addresses (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  label text null,
  address text not null,
  lat double precision null,
  lon double precision null,
  is_default boolean not null default false,
  created_at timestamp with time zone not null default now(),
  constraint user_addresses_pkey primary key (id),
  constraint user_addresses_user_id_fkey foreign KEY (user_id) references users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;
