#!/usr/bin/env bash
# Regenerate master.sql from the per-file sources, in dependency order.
# Edit files under tables/ functions/ policies/, then run this to refresh master.sql.
set -euo pipefail
cd "$(dirname "$0")"

{
  cat <<'HEADER'
-- ============================================================
-- Sariko — MASTER schema (AUTO-GENERATED by build_master.sh — do not edit by hand)
-- Run ONCE against a fresh database (paste into Supabase SQL Editor) to provision
-- the full schema in order: tables -> functions/triggers -> RLS policies.
-- To change the schema, edit files under tables/ functions/ policies/ and re-run
-- ./build_master.sh
-- ============================================================
HEADER

  for f in tables/*.sql functions/functions.sql policies/rls.sql; do
    printf '\n\n-- >>>>>>>>>>>>>>>>>>>>  %s  <<<<<<<<<<<<<<<<<<<<\n\n' "$f"
    cat "$f"
  done
} > master.sql

echo "Wrote $(pwd)/master.sql"
