-- ============================================================
-- Sariko Database Schema (consolidated from v1 + v2)
-- Source of truth: Supabase production (v2)
-- ============================================================


--- Nếu sau này cần giữ lại order history cho audit/accounting, thì đổi orders.user_id từ CASCADE sang SET NULL. Nhưng MVP thì CASCADE OK.

-- 1. USERS
create table public.users (
  id uuid not null default gen_random_uuid (),
  email text not null,
  name text null,
  phone text null,
  role text null default 'customer'::text,
  is_seller boolean null default false,
  avatar_url text null,
  preferred_language text null,
  created_at timestamp without time zone null default now(),
  updated_at timestamp without time zone null default now(),
  constraint users_pkey primary key (id),
  constraint users_email_key unique (email),
  constraint users_role_check check (
    (role = any (array['customer'::text, 'seller'::text]))
  )
) TABLESPACE pg_default;

-- 2. USER ADDRESSES
create table public.user_addresses (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  label text null,
  address text not null,
  lat double precision null,
  lon double precision null,
  is_default boolean not null default false,
  created_at timestamp with time zone not null default now(),
  constraint user_addresses_pkey primary key (id),
  constraint user_addresses_user_id_fkey foreign key (user_id) references users (id) on update cascade on delete cascade
) TABLESPACE pg_default;

-- 3. SELLER PROFILES
create table public.seller_profiles (
  id uuid not null default gen_random_uuid (),
  user_id uuid null,
  store_name text not null,
  description text null,
  avatar_url text null,
  cover_url text null,
  address text null,
  lat numeric null,
  lon numeric null,
  is_open boolean null default true,
  opening_time time without time zone null,
  closing_time time without time zone null,
  is_verified boolean null default false,
  created_at timestamp without time zone null default now(),
  slug text not null,
  phone text null,
  constraint seller_profiles_pkey primary key (id),
  constraint seller_profiles_slug_key unique (slug),
  constraint seller_profiles_user_id_fkey foreign KEY (user_id) references users (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_seller_location on public.seller_profiles using btree (lat, lon) TABLESPACE pg_default;

-- 4. MENU CATEGORIES
create table public.menu_categories (
  id uuid not null default gen_random_uuid (),
  seller_id uuid null,
  name text not null,
  sort_order integer null default 0,
  is_active boolean null default true,
  created_at timestamp without time zone null default now(),
  updated_at timestamp without time zone null default now(),
  constraint menu_categories_pkey primary key (id),
  constraint menu_categories_seller_id_fkey foreign key (seller_id) references seller_profiles (id) on delete cascade
) TABLESPACE pg_default;

-- 5. FOOD ITEMS
create table public.food_items (
  id uuid not null default gen_random_uuid (),
  seller_id uuid null,
  category_id uuid null,
  name text not null,
  description text null,
  price numeric not null,
  unit_label text null,
  min_quantity integer null default 1,
  quantity_step integer null default 1,
  preorder_day integer null default 0,
  is_available boolean null default true,
  image_url text null,
  created_at timestamp without time zone null default now(),
  price_text text null,
  is_featured boolean not null default false,
  constraint food_items_pkey primary key (id),
  constraint food_items_category_id_fkey foreign KEY (category_id) references menu_categories (id) on delete set null,
  constraint food_items_seller_id_fkey foreign KEY (seller_id) references seller_profiles (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_food_items_seller on public.food_items using btree (seller_id) TABLESPACE pg_default;

-- 6. CARTS
create table public.carts (
  id uuid not null default gen_random_uuid (),
  user_id uuid null,
  seller_id uuid null,
  created_at timestamp without time zone null default now(),
  constraint carts_pkey primary key (id),
  constraint carts_seller_id_fkey foreign key (seller_id) references seller_profiles (id),
  constraint carts_user_id_fkey foreign key (user_id) references users (id) on delete cascade
) TABLESPACE pg_default;

-- 7. CART ITEMS
create table public.cart_items (
  id uuid not null default gen_random_uuid (),
  cart_id uuid null,
  food_item_id uuid null,
  quantity integer not null,
  constraint cart_items_pkey primary key (id),
  constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (id) on delete cascade,
  constraint cart_items_food_item_id_fkey foreign key (food_item_id) references food_items (id),
  constraint cart_items_quantity_check check ((quantity > 0))
) TABLESPACE pg_default;

-- 8. ORDERS
create table public.orders (
  id uuid not null default gen_random_uuid (),
  user_id uuid null,
  seller_id uuid null,
  status text null default 'pending'::text,
  total_amount numeric not null,
  delivery_fee numeric null default 0,
  payment_status text null default 'pending'::text,
  delivery_method text null,
  delivery_address text null,
  note text null,
  created_at timestamp without time zone null default now(),
  delivery_lat double precision null,
  delivery_lon double precision null,
  quotation_id text null,
  cancellation_reason text null,
  transaction_ref text null,
  seller_user_id uuid null,
  constraint orders_pkey primary key (id),
  constraint orders_seller_id_fkey foreign KEY (seller_id) references seller_profiles (id),
  constraint orders_user_id_fkey foreign KEY (user_id) references users (id),
  constraint orders_delivery_method_check check (
    (
      delivery_method = any (array['pickup'::text, 'delivery'::text])
    )
  ),
  constraint orders_payment_status_check check (
    (
      payment_status = any (
        array['pending'::text, 'paid'::text, 'failed'::text]
      )
    )
  ),
  constraint orders_status_check check (
    (
      status = any (
        array[
          'pending'::text,
          'confirmed'::text,
          'ready'::text,
          'done'::text,
          'cancelled'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_orders_user on public.orders using btree (user_id) TABLESPACE pg_default;

create index IF not exists idx_orders_seller on public.orders using btree (seller_id) TABLESPACE pg_default;

-- 9. ORDER ITEMS (SNAPSHOT)
create table public.order_items (
  id uuid not null default gen_random_uuid (),
  order_id uuid null,
  food_item_id uuid null,
  name_snapshot text null,
  price_snapshot numeric null,
  unit_label_snapshot text null,
  quantity integer not null,
  constraint order_items_pkey primary key (id),
  constraint order_items_food_item_id_fkey foreign key (food_item_id) references food_items (id),
  constraint order_items_order_id_fkey foreign key (order_id) references orders (id) on delete cascade
) TABLESPACE pg_default;

-- 10. REVIEWS
create table public.reviews (
  id uuid not null default gen_random_uuid (),
  order_id uuid null,
  seller_id uuid null,
  user_id uuid null,
  rating integer null,
  comment text null,
  created_at timestamp without time zone null default now(),
  constraint reviews_pkey primary key (id),
  constraint reviews_order_id_fkey foreign key (order_id) references orders (id) on delete cascade,
  constraint reviews_seller_id_fkey foreign key (seller_id) references seller_profiles (id),
  constraint reviews_user_id_fkey foreign key (user_id) references users (id),
  constraint reviews_rating_check check (((rating >= 1) and (rating <= 5)))
) TABLESPACE pg_default;

-- 11. PAYMENTS
create table public.payments (
  id uuid not null default gen_random_uuid (),
  order_id uuid null,
  method text null,
  amount numeric null,
  status text null,
  transaction_ref text null,
  created_at timestamp without time zone null default now(),
  constraint payments_pkey primary key (id),
  constraint payments_order_id_fkey foreign key (order_id) references orders (id) on delete cascade
) TABLESPACE pg_default;

-- 12. DELIVERIES
create table public.deliveries (
  id uuid not null default gen_random_uuid (),
  order_id uuid null,
  provider text null,
  status text null,
  tracking_url text null,
  driver_name text null,
  driver_phone text null,
  created_at timestamp without time zone null default now(),
  estimated_pickup_time timestamp without time zone null,
  share_link text null,
  driver_plate text null,
  lalamove_order_id text null,
  rebook_count integer null default 0,
  constraint deliveries_pkey primary key (id),
  constraint deliveries_order_id_fkey foreign KEY (order_id) references orders (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_deliveries_order_id on public.deliveries using btree (order_id) TABLESPACE pg_default;

create index IF not exists idx_deliveries_lalamove_order_id on public.deliveries using btree (lalamove_order_id) TABLESPACE pg_default;