-- ============================================================
-- Sariko — MASTER schema (AUTO-GENERATED by build_master.sh — do not edit by hand)
-- Run ONCE against a fresh database (paste into Supabase SQL Editor) to provision
-- the full schema in order: tables -> functions/triggers -> RLS policies.
-- To change the schema, edit files under tables/ functions/ policies/ and re-run
-- ./build_master.sh
-- ============================================================


-- >>>>>>>>>>>>>>>>>>>>  tables/00_admin_config.sql  <<<<<<<<<<<<<<<<<<<<

-- ============================================================
-- Admin config: tier subscription + tax settings
-- Created FIRST — seller_profiles.tier and order snapshots FK / read from here.
-- ============================================================

create table public.admin_tier_config (
  tier            text    not null,
  commission_rate numeric not null,
  monthly_fee_usd numeric not null default 0,
  max_items       integer,      -- null = unlimited
  max_categories  integer,      -- null = unlimited
  constraint admin_tier_config_pkey primary key (tier)
);

insert into public.admin_tier_config (tier, commission_rate, monthly_fee_usd, max_items, max_categories)
values
  ('founding',   0,    0,  null, null),  -- 0% commission, early adopter sellers
  ('community',  0.19, 0,  3,    1),
  ('tindahan',   0.17, 29, 30,   5),
  ('negosyo',    0.15, 49, 90,   10),
  ('enterprise', 0.13, 89, null, null),
  ('bodega',     0,    0,  null, null)   -- negotiated: rate set via seller_profiles.commission_rate_override
on conflict (tier) do nothing;

comment on table public.admin_tier_config is
  'Source of truth for tier definitions. Changing commission_rate here does NOT affect past orders.';
comment on column public.admin_tier_config.commission_rate is
  'Default rate for this tier. Bodega = 0 because rate is negotiated per seller.';


create table public.admin_tax_config (
  key         text        not null,
  rate        numeric     not null,
  description text,
  updated_at  timestamptz not null default now(),
  constraint admin_tax_config_pkey primary key (key)
);

insert into public.admin_tax_config (key, rate, description)
values
  ('vat_rate',                   0.10,        'VAT on Sariko commission (platform service fee to sellers)'),
  ('withholding_rate_goods',     0.01,        'Withholding tax for goods sellers (imported products, dry goods)'),
  ('withholding_rate_services',  0.02,        'Withholding tax for service sellers (food, tutoring, tailoring)'),
  ('annual_revenue_threshold',   100000000,   'Annual VND threshold above which withholding tax applies')
on conflict (key) do nothing;

comment on table public.admin_tax_config is
  'Platform-wide tax settings. Adjustable by admin. Changes apply to new orders only.';


-- >>>>>>>>>>>>>>>>>>>>  tables/01_users.sql  <<<<<<<<<<<<<<<<<<<<

-- ============================================================
-- Users + user addresses
-- public.users.id mirrors auth.users.id (populated by the handle_user_create
-- trigger in functions/functions.sql).
-- ============================================================

create table public.users (
  id uuid not null default gen_random_uuid (),
  email text not null,
  name text null,
  phone text null,
  role text null default 'customer'::text,
  created_at timestamp without time zone null default now(),
  is_seller boolean null default false,
  updated_at timestamp without time zone null default now(),
  avatar_url text null,
  preferred_language text null,
  constraint users_pkey primary key (id),
  constraint users_email_key unique (email),
  constraint users_role_check check (
    (role = any (array['customer'::text, 'seller'::text]))
  )
) TABLESPACE pg_default;


create table public.user_addresses (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  label text null,
  address text not null,
  lat double precision null,
  lon double precision null,
  is_default boolean not null default false,
  created_at timestamp with time zone not null default now(),
  constraint user_addresses_pkey primary key (id),
  constraint user_addresses_user_id_fkey foreign KEY (user_id) references users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;


-- >>>>>>>>>>>>>>>>>>>>  tables/02_seller_profiles.sql  <<<<<<<<<<<<<<<<<<<<

-- ============================================================
-- Seller profiles
-- tier FK → admin_tier_config; status coming_soon | active.
-- ============================================================

create table public.seller_profiles (
  id uuid not null default gen_random_uuid (),
  user_id uuid null,
  store_name text not null,
  description text null,
  avatar_url text null,
  cover_url text null,
  address text null,
  lat numeric null,
  lon numeric null,
  is_open boolean null default true,
  opening_time time without time zone null,
  closing_time time without time zone null,
  is_verified boolean null default false,
  created_at timestamp without time zone null default now(),
  slug text not null,
  phone text null,
  tier text not null default 'community'::text,
  commission_rate_override numeric null,
  bank_account_number text null,
  bank_name text null,
  bank_account_holder text null,
  tax_category text not null default 'services'::text,
  status text not null default 'coming_soon'::text,
  constraint seller_profiles_pkey primary key (id),
  constraint seller_profiles_slug_key unique (slug),
  constraint seller_profiles_tier_fkey foreign KEY (tier) references admin_tier_config (tier),
  constraint seller_profiles_user_id_fkey foreign KEY (user_id) references users (id) on delete CASCADE,
  constraint seller_profiles_tax_category_check check (
    (tax_category = any (array['goods'::text, 'services'::text]))
  ),
  constraint seller_profiles_status_check check (
    (status = any (array['coming_soon'::text, 'active'::text]))
  )
) TABLESPACE pg_default;

create index IF not exists idx_seller_location on public.seller_profiles using btree (lat, lon) TABLESPACE pg_default;

comment on column public.seller_profiles.commission_rate_override is
  'Only set for bodega tier. NULL = use admin_tier_config.commission_rate.';


-- >>>>>>>>>>>>>>>>>>>>  tables/03_menu.sql  <<<<<<<<<<<<<<<<<<<<

-- ============================================================
-- Menu: categories + food items (both scoped to a seller_profile)
-- ============================================================

create table public.menu_categories (
  id uuid not null default gen_random_uuid (),
  seller_id uuid null,
  name text not null,
  sort_order integer null default 0,
  is_active boolean null default true,
  created_at timestamp without time zone null default now(),
  updated_at timestamp without time zone null default now(),
  constraint menu_categories_pkey primary key (id),
  constraint menu_categories_seller_id_fkey foreign KEY (seller_id) references seller_profiles (id) on delete CASCADE
) TABLESPACE pg_default;


create table public.food_items (
  id uuid not null default gen_random_uuid (),
  seller_id uuid null,
  category_id uuid null,
  name text not null,
  description text null,
  price numeric not null,
  unit_label text null,
  min_quantity integer null default 1,
  quantity_step integer null default 1,
  preorder_day integer null default 0,
  is_available boolean null default true,
  image_url text null,
  created_at timestamp without time zone null default now(),
  price_text text null,
  is_featured boolean not null default false,
  constraint food_items_pkey primary key (id),
  constraint food_items_category_id_fkey foreign KEY (category_id) references menu_categories (id) on delete set null,
  constraint food_items_seller_id_fkey foreign KEY (seller_id) references seller_profiles (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_food_items_seller on public.food_items using btree (seller_id) TABLESPACE pg_default;


-- >>>>>>>>>>>>>>>>>>>>  tables/04_carts.sql  <<<<<<<<<<<<<<<<<<<<

-- ============================================================
-- Carts + cart items (one active cart per user, single-seller)
-- ============================================================

create table public.carts (
  id uuid not null default gen_random_uuid (),
  user_id uuid null,
  seller_id uuid null,
  created_at timestamp without time zone null default now(),
  constraint carts_pkey primary key (id),
  constraint carts_seller_id_fkey foreign KEY (seller_id) references seller_profiles (id),
  constraint carts_user_id_fkey foreign KEY (user_id) references users (id) on delete CASCADE
) TABLESPACE pg_default;


create table public.cart_items (
  id uuid not null default gen_random_uuid (),
  cart_id uuid null,
  food_item_id uuid null,
  quantity integer not null,
  constraint cart_items_pkey primary key (id),
  constraint cart_items_cart_id_fkey foreign KEY (cart_id) references carts (id) on delete CASCADE,
  constraint cart_items_food_item_id_fkey foreign KEY (food_item_id) references food_items (id),
  constraint cart_items_quantity_check check ((quantity > 0))
) TABLESPACE pg_default;


-- >>>>>>>>>>>>>>>>>>>>  tables/05_admin_payouts.sql  <<<<<<<<<<<<<<<<<<<<

-- ============================================================
-- Admin payout batches — one row per weekly payout run per seller.
-- Created BEFORE orders because orders.payout_id references it.
-- ============================================================

create table public.admin_payouts (
  id                 uuid        not null default gen_random_uuid(),
  seller_id          uuid        not null,  -- FK → seller_profiles.id
  period_start       date        not null,
  period_end         date        not null,
  order_count        integer     not null default 0,
  total_subtotal     numeric     not null default 0,
  total_commission   numeric     not null default 0,
  total_vat          numeric     not null default 0,
  gross_payout       numeric     not null default 0,  -- subtotal - commission - vat
  withholding_rate   numeric     not null default 0,  -- snapshot at payout time
  withholding_amount numeric     not null default 0,
  net_payout         numeric     not null default 0,  -- gross_payout - withholding
  status             text        not null default 'pending'
    constraint admin_payouts_status_check check (
      status = any (array['pending', 'processing', 'completed', 'failed'])
    ),
  note               text,
  paid_at            timestamptz,
  created_at         timestamptz not null default now(),
  constraint admin_payouts_pkey primary key (id),
  constraint admin_payouts_seller_id_fkey foreign KEY (seller_id) references public.seller_profiles (id)
);

create index IF not exists idx_admin_payouts_seller_id on public.admin_payouts (seller_id);
create index IF not exists idx_admin_payouts_status on public.admin_payouts (status);

comment on table public.admin_payouts is
  'Weekly payout batch per seller. One row = one bank transfer to seller.';


-- >>>>>>>>>>>>>>>>>>>>  tables/06_orders.sql  <<<<<<<<<<<<<<<<<<<<

-- ============================================================
-- Orders + order items (snapshot)
-- Commission + VAT are snapshotted at creation and never change after insert.
-- payout_amount = subtotal - commission_amount - vat_amount (delivery fee excluded).
-- ============================================================

create table public.orders (
  id uuid not null default gen_random_uuid (),
  user_id uuid null,
  seller_id uuid null,
  status text null default 'pending'::text,
  total_amount numeric not null,
  delivery_fee numeric null default 0,
  payment_status text null default 'pending'::text,
  delivery_method text null,
  delivery_address text null,
  note text null,
  created_at timestamp without time zone null default now(),
  delivery_lat double precision null,
  delivery_lon double precision null,
  quotation_id text null,
  cancellation_reason text null,
  transaction_ref text null,
  seller_user_id uuid null,
  subtotal numeric not null default 0,
  commission_rate numeric not null default 0,   -- snapshot from seller tier
  commission_amount numeric not null default 0,
  payout_amount numeric not null default 0,
  payout_status text not null default 'pending'::text,
  payout_id uuid null,
  vat_rate numeric not null default 0,           -- snapshot from admin_tax_config
  vat_amount numeric not null default 0,
  ipn_data jsonb null,
  delivery_appointment timestamp with time zone null,
  payment_create_date text null,
  constraint orders_pkey primary key (id),
  constraint orders_payout_id_fkey foreign KEY (payout_id) references admin_payouts (id) on delete set null,
  constraint orders_user_id_fkey foreign KEY (user_id) references users (id),
  constraint orders_seller_id_fkey foreign KEY (seller_id) references seller_profiles (id),
  constraint orders_payment_status_check check (
    (payment_status = any (array['pending'::text, 'paid'::text, 'failed'::text]))
  ),
  constraint orders_delivery_method_check check (
    (delivery_method = any (array['pickup'::text, 'delivery'::text]))
  ),
  constraint orders_status_check check (
    (status = any (
      array[
        'pending'::text, 'confirmed'::text, 'ready'::text,
        'done'::text, 'cancelled'::text, 'delivery_failed'::text
      ]
    ))
  ),
  constraint orders_payout_status_check check (
    (payout_status = any (array['pending'::text, 'processing'::text, 'paid_out'::text]))
  )
) TABLESPACE pg_default;

create index IF not exists idx_orders_user on public.orders using btree (user_id) TABLESPACE pg_default;
create index IF not exists idx_orders_seller on public.orders using btree (seller_id) TABLESPACE pg_default;


create table public.order_items (
  id uuid not null default gen_random_uuid (),
  order_id uuid null,
  food_item_id uuid null,
  name_snapshot text null,
  price_snapshot numeric null,
  unit_label_snapshot text null,
  quantity integer not null,
  constraint order_items_pkey primary key (id),
  constraint order_items_food_item_id_fkey foreign KEY (food_item_id) references food_items (id),
  constraint order_items_order_id_fkey foreign KEY (order_id) references orders (id) on delete CASCADE
) TABLESPACE pg_default;


-- >>>>>>>>>>>>>>>>>>>>  tables/07_reviews.sql  <<<<<<<<<<<<<<<<<<<<

-- ============================================================
-- Reviews (buyer rates a completed order / seller)
-- ============================================================

create table public.reviews (
  id uuid not null default gen_random_uuid (),
  order_id uuid null,
  seller_id uuid null,
  user_id uuid null,
  rating integer null,
  comment text null,
  created_at timestamp without time zone null default now(),
  constraint reviews_pkey primary key (id),
  constraint reviews_order_id_fkey foreign KEY (order_id) references orders (id) on delete CASCADE,
  constraint reviews_seller_id_fkey foreign KEY (seller_id) references seller_profiles (id),
  constraint reviews_user_id_fkey foreign KEY (user_id) references users (id),
  constraint reviews_rating_check check (((rating >= 1) and (rating <= 5)))
) TABLESPACE pg_default;


-- >>>>>>>>>>>>>>>>>>>>  tables/08_deliveries.sql  <<<<<<<<<<<<<<<<<<<<

-- ============================================================
-- Deliveries (Lalamove booking + driver tracking, per order)
-- ============================================================

create table public.deliveries (
  id uuid not null default gen_random_uuid (),
  order_id uuid null,
  provider text null,
  status text null,
  tracking_url text null,
  driver_name text null,
  driver_phone text null,
  created_at timestamp without time zone null default now(),
  estimated_pickup_time timestamp without time zone null,
  share_link text null,
  driver_plate text null,
  lalamove_order_id text null,
  rebook_count integer null default 0,
  user_id uuid null,
  seller_user_id uuid null,
  constraint deliveries_pkey primary key (id),
  constraint deliveries_order_id_fkey foreign KEY (order_id) references orders (id) on delete CASCADE,
  constraint deliveries_seller_user_id_fkey foreign KEY (seller_user_id) references users (id),
  constraint deliveries_user_id_fkey foreign KEY (user_id) references users (id)
) TABLESPACE pg_default;

create index IF not exists idx_deliveries_order_id on public.deliveries using btree (order_id) TABLESPACE pg_default;
create index IF not exists idx_deliveries_lalamove_order_id on public.deliveries using btree (lalamove_order_id) TABLESPACE pg_default;
create index IF not exists idx_deliveries_user_id on public.deliveries using btree (user_id) TABLESPACE pg_default;
create index IF not exists idx_deliveries_seller_user_id on public.deliveries using btree (seller_user_id) TABLESPACE pg_default;


-- >>>>>>>>>>>>>>>>>>>>  tables/09_refunds.sql  <<<<<<<<<<<<<<<<<<<<

-- ============================================================
-- Refunds (VNPay refund tracking) — created before payments (payments.refund_id FK).
-- ============================================================

create table public.refunds (
  id uuid not null default gen_random_uuid (),
  order_id uuid not null,
  amount numeric not null,
  reason text not null,
  status text not null default 'pending'::text,
  original_txn_ref text null,
  ipn_data jsonb null,
  vnpay_refund_ref text null,
  created_at timestamp with time zone null default now(),
  processed_at timestamp with time zone null,
  note text null,
  payment_create_date text null,
  constraint refunds_pkey primary key (id),
  constraint refunds_order_id_fkey foreign KEY (order_id) references orders (id),
  constraint refunds_reason_check check (
    (reason = any (array['buyer_cancel'::text, 'driver_booking_failed'::text]))
  ),
  constraint refunds_status_check check (
    (status = any (array['pending'::text, 'processed'::text, 'failed'::text]))
  )
) TABLESPACE pg_default;


-- >>>>>>>>>>>>>>>>>>>>  tables/10_payments.sql  <<<<<<<<<<<<<<<<<<<<

-- ============================================================
-- Payments (VNPay charge / refund records)
-- ============================================================

create table public.payments (
  id uuid not null default gen_random_uuid (),
  order_id uuid null,
  method text null,
  amount numeric null,
  status text null,
  transaction_ref text null,
  created_at timestamp without time zone null default now(),
  type text not null default 'charge'::text,
  vnp_transaction_no text null,
  refund_id uuid null,
  constraint payments_pkey primary key (id),
  constraint payments_order_id_fkey foreign KEY (order_id) references orders (id) on delete CASCADE,
  constraint payments_refund_id_fkey foreign KEY (refund_id) references refunds (id) on delete set null,
  constraint payments_type_check check (
    (type = any (array['charge'::text, 'refund'::text]))
  )
) TABLESPACE pg_default;


-- >>>>>>>>>>>>>>>>>>>>  tables/11_chat.sql  <<<<<<<<<<<<<<<<<<<<

-- ============================================================
-- Chat: buyer <-> seller messaging. One conversation per (buyer, seller) pair.
-- Named chat_* on purpose — Supabase ships realtime.messages already.
-- Pin / soft-delete are per participant (buyer_* and seller_* columns).
--
-- The bump trigger lives in functions/functions.sql; grants, realtime
-- publication, and RLS live in policies/rls.sql.
-- ============================================================

create table public.chat_conversations (
  id uuid not null default gen_random_uuid (),
  buyer_id uuid not null,
  seller_id uuid not null,
  last_message_at timestamp with time zone null,
  last_message_text text null,
  buyer_pinned_at timestamp with time zone null,
  seller_pinned_at timestamp with time zone null,
  buyer_deleted_at timestamp with time zone null,
  seller_deleted_at timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  constraint chat_conversations_pkey primary key (id),
  constraint chat_conversations_buyer_seller_key unique (buyer_id, seller_id),
  constraint chat_conversations_buyer_id_fkey foreign KEY (buyer_id) references users (id) on delete CASCADE,
  constraint chat_conversations_seller_id_fkey foreign KEY (seller_id) references seller_profiles (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_chat_conversations_buyer on public.chat_conversations using btree (buyer_id) TABLESPACE pg_default;
create index IF not exists idx_chat_conversations_seller on public.chat_conversations using btree (seller_id) TABLESPACE pg_default;


create table public.chat_messages (
  id uuid not null default gen_random_uuid (),
  conversation_id uuid not null,
  sender_id uuid not null,
  body text not null,
  created_at timestamp with time zone not null default now(),
  read_at timestamp with time zone null,
  constraint chat_messages_pkey primary key (id),
  constraint chat_messages_conversation_id_fkey foreign KEY (conversation_id) references chat_conversations (id) on delete CASCADE,
  constraint chat_messages_sender_id_fkey foreign KEY (sender_id) references users (id),
  constraint chat_messages_body_check check ((char_length(btrim(body)) > 0))
) TABLESPACE pg_default;

create index IF not exists idx_chat_messages_conversation on public.chat_messages using btree (conversation_id, created_at desc) TABLESPACE pg_default;


-- >>>>>>>>>>>>>>>>>>>>  functions/functions.sql  <<<<<<<<<<<<<<<<<<<<

-- ============================================================
-- Functions & triggers
-- The trigger that binds handle_user_create to auth.users is managed in the
-- Supabase dashboard (Auth hooks), not here.
-- ============================================================

-- ⚠️ WARNING: the two handle_user_create definitions below share the SAME name,
-- so the second CREATE OR REPLACE OVERWRITES the first — only the UPDATE body
-- survives. This looks like a latent bug (the INSERT-on-signup body is lost).
-- Preserved verbatim from the original functions.sql; review before relying on it.

-- Insert a public.users row after auth.users creates a record.
create or replace function public.handle_user_create()
returns trigger as
$$
begin
    if not exists (select 1 from public.users where id = new.id) then
        insert into public.users (
          id, email, name, is_seller, created_at, updated_at
        ) values (
            new.id,
            new.email,
            new.raw_user_meta_data->>'fullname',
            new.raw_user_meta_data->>'is_seller',
            new.created_at,
            new.updated_at
        );
    end if;
    return new;
end;
$$
language plpgsql security definer;

-- Sync avatar/phone from auth metadata (⚠️ overwrites the definition above).
create or replace function public.handle_user_create()
returns trigger as
$$
begin
    update public.users
    set
        avatar_url = new.raw_user_meta_data->>'avatar_url',
        phone = new.phone,
        updated_at = new.updated_at
    where id = new.id;
    return new;
end;
$$
language plpgsql security definer;


-- Update order + payment status together (used by the VNPay flow).
create or replace function update_order_payment_status(
  p_order_id uuid,
  p_status text,
  p_transaction_ref text default null
) returns void as
$$
begin
  update public.orders
  set payment_status = p_status
  where id = p_order_id;

  if p_transaction_ref is not null then
    update public.payments
    set status = p_status, transaction_ref = p_transaction_ref
    where order_id = p_order_id;
  end if;
end;
$$
language plpgsql security definer
set search_path = public;


-- Chat: on a new message, refresh the conversation preview / ordering columns
-- AND resurface the thread for anyone who had soft-deleted it (new activity un-hides).
-- SECURITY DEFINER so an authenticated message insert can update the parent
-- conversation without needing an UPDATE grant / RLS policy on that role.
create or replace function public.bump_chat_conversation () returns trigger
  language plpgsql
  security definer
  set search_path = public
as $$
begin
  update public.chat_conversations
     set last_message_at = new.created_at,
         last_message_text = new.body,
         buyer_deleted_at = null,
         seller_deleted_at = null
   where id = new.conversation_id;
  return new;
end;
$$;

drop trigger if exists on_new_chat_message on public.chat_messages;
create trigger on_new_chat_message
  after insert on public.chat_messages
  for each row
  execute function public.bump_chat_conversation ();


-- >>>>>>>>>>>>>>>>>>>>  policies/rls.sql  <<<<<<<<<<<<<<<<<<<<

-- ============================================================
-- Row Level Security — all policies, organized by table.
-- Clients (authenticated) read/write some tables directly via Supabase;
-- everything else goes through the backend (service_role, bypasses RLS).
-- Idempotent: every policy is dropped-if-exists before create.
--
-- NOTE: image uploads no longer use storage RLS — they go through backend
-- endpoints (service role). See archive/storage_policies.sql for the retired
-- storage.objects policies. Storage reads stay public via the bucket setting.
-- ============================================================

alter table public.users enable row level security;
alter table public.seller_profiles enable row level security;
alter table public.menu_categories enable row level security;
alter table public.food_items enable row level security;
alter table public.carts enable row level security;
alter table public.cart_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.reviews enable row level security;
alter table public.payments enable row level security;
alter table public.deliveries enable row level security;
alter table public.chat_conversations enable row level security;
alter table public.chat_messages enable row level security;

-- ── users ──────────────────────────────────────────────────────────────────
drop policy if exists "users can read own profile" on public.users;
create policy "users can read own profile"
on public.users for select
using (id = auth.uid());

drop policy if exists "users can update own profile" on public.users;
create policy "users can update own profile"
on public.users for update
using (id = auth.uid());

-- ── seller_profiles ────────────────────────────────────────────────────────
-- Public can browse storefronts; a seller edits only their own row.
-- NOTE: "public read" exposes every column (incl. user_id, phone) to anon.
-- Keep sensitive/column-shaped reads going through the backend.
drop policy if exists "seller read own profile" on public.seller_profiles;  -- superseded by public read
drop policy if exists "public read seller profiles" on public.seller_profiles;
create policy "public read seller profiles"
on public.seller_profiles for select
using (true);

drop policy if exists "seller update own profile" on public.seller_profiles;
create policy "seller update own profile"
on public.seller_profiles for update
using (user_id = auth.uid())
with check (user_id = auth.uid());

-- ── menu_categories ────────────────────────────────────────────────────────
drop policy if exists "public read categories" on public.menu_categories;
create policy "public read categories"
on public.menu_categories for select
using (true);

drop policy if exists "seller manage categories" on public.menu_categories;
create policy "seller manage categories"
on public.menu_categories for all
using (seller_id in (select id from public.seller_profiles where user_id = auth.uid()))
with check (seller_id in (select id from public.seller_profiles where user_id = auth.uid()));

-- ── food_items ─────────────────────────────────────────────────────────────
drop policy if exists "public read food" on public.food_items;
create policy "public read food"
on public.food_items for select
using (is_available = true);

drop policy if exists "seller manage food" on public.food_items;
create policy "seller manage food"
on public.food_items for all
using (seller_id in (select id from public.seller_profiles where user_id = auth.uid()))
with check (seller_id in (select id from public.seller_profiles where user_id = auth.uid()));

-- ── carts / cart_items ─────────────────────────────────────────────────────
drop policy if exists "user manage own cart" on public.carts;
create policy "user manage own cart"
on public.carts for all
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "user manage own cart items" on public.cart_items;
create policy "user manage own cart items"
on public.cart_items for all
using (cart_id in (select id from public.carts where user_id = auth.uid()))
with check (cart_id in (select id from public.carts where user_id = auth.uid()));

-- ── orders / order_items ───────────────────────────────────────────────────
drop policy if exists "user read own orders" on public.orders;
create policy "user read own orders"
on public.orders for select
using (
    user_id = auth.uid()
    or seller_id in (select id from public.seller_profiles where user_id = auth.uid())
);

drop policy if exists "user create order" on public.orders;
create policy "user create order"
on public.orders for insert
with check (user_id = auth.uid());

drop policy if exists "seller update order status" on public.orders;
create policy "seller update order status"
on public.orders for update
using (seller_id in (select id from public.seller_profiles where user_id = auth.uid()));

drop policy if exists "read order items of accessible orders" on public.order_items;
create policy "read order items of accessible orders"
on public.order_items for select
using (
    order_id in (
        select id from public.orders
        where user_id = auth.uid()
        or seller_id in (select id from public.seller_profiles where user_id = auth.uid())
    )
);

-- ── reviews ────────────────────────────────────────────────────────────────
drop policy if exists "public read reviews" on public.reviews;
create policy "public read reviews"
on public.reviews for select
using (true);

drop policy if exists "user write own review" on public.reviews;
create policy "user write own review"
on public.reviews for insert
with check (user_id = auth.uid());

-- ── payments ───────────────────────────────────────────────────────────────
drop policy if exists "user read own payments" on public.payments;
create policy "user read own payments"
on public.payments for select
using (order_id in (select id from public.orders where user_id = auth.uid()));

-- ── deliveries ─────────────────────────────────────────────────────────────
drop policy if exists "read delivery of accessible orders" on public.deliveries;
create policy "read delivery of accessible orders"
on public.deliveries for select
using (
    order_id in (
        select id from public.orders
        where user_id = auth.uid()
        or seller_id in (select id from public.seller_profiles where user_id = auth.uid())
    )
);

-- ── chat ───────────────────────────────────────────────────────────────────
-- RLS filters rows, but the authenticated role still needs table privileges.
-- Frontend reads history + sends messages directly; it reads chat_conversations
-- because the message policies reference it in a subquery. No anon access.
grant select on public.chat_conversations to authenticated;
grant select, insert on public.chat_messages to authenticated;
grant all on public.chat_conversations to service_role;
grant all on public.chat_messages to service_role;

-- Broadcast message inserts to subscribed participants (RLS still filters rows).
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'chat_messages'
  ) then
    alter publication supabase_realtime add table public.chat_messages;
  end if;
end $$;

drop policy if exists "participant read conversation" on public.chat_conversations;
create policy "participant read conversation"
on public.chat_conversations for select
using (
  buyer_id = auth.uid()
  or seller_id in (select id from public.seller_profiles where user_id = auth.uid())
);

drop policy if exists "participant update conversation" on public.chat_conversations;
create policy "participant update conversation"
on public.chat_conversations for update
using (
  buyer_id = auth.uid()
  or seller_id in (select id from public.seller_profiles where user_id = auth.uid())
);

drop policy if exists "participant read messages" on public.chat_messages;
create policy "participant read messages"
on public.chat_messages for select
using (
  conversation_id in (
    select id from public.chat_conversations
    where buyer_id = auth.uid()
       or seller_id in (select id from public.seller_profiles where user_id = auth.uid())
  )
);

drop policy if exists "participant send message" on public.chat_messages;
create policy "participant send message"
on public.chat_messages for insert
with check (
  sender_id = auth.uid()
  and conversation_id in (
    select id from public.chat_conversations
    where buyer_id = auth.uid()
       or seller_id in (select id from public.seller_profiles where user_id = auth.uid())
  )
);

drop policy if exists "recipient mark read" on public.chat_messages;
create policy "recipient mark read"
on public.chat_messages for update
using (
  conversation_id in (
    select id from public.chat_conversations
    where buyer_id = auth.uid()
       or seller_id in (select id from public.seller_profiles where user_id = auth.uid())
  )
);
