on:
  push:
    branches:
      - feature/cicd
jobs:
  test:
    name: job name
    runs-on:
      labels: ec2-sariko-app
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Build and push docker image
        run: |
          ./backend/docker_build_and_push.sh

      - name: 
        run: |
          source /home/ubuntu/venv-app-sariko/bin/activate
          pytest tests/backend -v
